### ISSUE TITLE
minimum version for YoonitCamera

### ISSUE THREAD

**Issue by fukemy** [Yoonit-Labs/ios-yoonit-facefy#10]
hi, today i tested YoonitCamera, but i got minimum version error when run pod, can u help? Thanks
```
pod 'YoonitCamera', :git => 'https://github.com/Yoonit-Labs/ios-yoonit-camera.git', :tag => '2.7.0'
```
![Screen Shot 2021-05-18 at 17 24 51](https://user-images.githubusercontent.com/8202437/118635776-2b3e2000-b7fe-11eb-8feb-f357de711911.png)

**Comment by TeruyaHaroldo** [comment]
Hi @fukemy 
Sorry for the delay. Have you tried cleaning the build?
