### ISSUE TITLE
a question about ML price

### ISSUE THREAD

**Issue by fukemy** [Yoonit-Labs/ios-yoonit-facefy#6]
hi, thanks you for great library, i want to ask a question: I found your library using google ML Kit to detect face action, so does it took price for this project? Thanks

**Comment by TeruyaHaroldo** [comment]
Hi @fukemy. Thanks for the compliment.
The answer for your question is: no.

**Comment by fukemy** [comment]
yeah, poor developer like this <3, thanks

**Comment by TeruyaHaroldo** [comment]
That's true @fukemy hahaha
Give a `star` :star: to ours repository, this help us a lot to maintain :wink:

Have you seen our [iOS Yoonit Camera](https://github.com/Yoonit-Labs/ios-yoonit-camera) and [NS Yoonit Camera](https://github.com/Yoonit-Labs/nativescript-yoonit-camera)? These libs uses this lib as dependency to analyse the face in real time.
